# CADEIA DE TEXTOS OU STRING ASPAS SIMPLES OU DUPLAS
# MODO DE MANIPULAR ESTES CARACTERES

#COMECA A CONTAR DO ZERO
#FATIAMENTO:

# EXEMPLO: FRASE =[9]
#  ESPAÇO TBM É CONTADO:
#  0                                                        20
# [C][U][R][S][O][][E][M][][V][I][D][E][O][][P][Y][T][H][O][N]
#                           9           13   15
#O 9 É A LETRA V
#DIFENCIA MAIUSCULA DE MINUSCULA O PYTHON
#FRASE[9:13]:COMEÇA NO 9 E VAI ATE O 13 SO QUE O 13 SERA EXCLUIDO
# FICA: VIDE O 0 NÃO ENTRA NA LISTA CASO QUEIRA PEGAR O O, COMEÇA A CONTAR DO  14
# FICARIA ASSIM: FRASE= [9:14]. REND

#POSSO FAZER FRASE= [9:21:2] COMEÇA NO 9 TERMINA NO 20(LEMBRANDO QUE CONTA
# O ZERO E OS ESPAÇOS )E O 2,PULA DE DOIS EM DOIS.

#FRASE=[:5] QUANDO EU NÃO COLOCO ONDE ELE VAI COMEÇAR FAZ DO ZERO ATE O 4
# FRASE=[15:] INDIQUEI O INICIO MAS NAO INDIQUEI O FINAL OU SEJA
# QUERO DO 15 ATE O FINAL DA FRASE.

#FRASE=[9::3] COMEÇA NO 9 E VAI ATE O FIM DA FRASE E PULE 3 EM 3

#ANALISE:
#len(frase) comprimento da frase

#frase.count('o') CONTAR QUANTAS VEZES APARECE A LETRA O.

#frase.count('o',0,13') CONTAGEM COM FATIAMENTO.QUANTAS VEZES APARECE
# A LETRA O ENTRE O 0 ATÉ O 12. O TREZE NÃO E CONTADO NO PYTHON DUVIDA
# OLHE  NO PARAGRAFO 14

#frase.find('deo')QUANTAS VEZES ELE ENCONTROU DEO DENTRO DA FRASE ACIMA:
#COMEÇANDO.
# frase=rfind =QUANTAS VEZES A PALAVRA OU LETRA APARECE NA ULTIMA POSIÇÃO.
#frase.find('android')QUANDO É COLOCADO UMA FRASE QUE NÃO EXISTE ELE MOSTRA -1
# ELE NÃO ENCONTROU NA FRASE COLOCADA.

# 'curso' in frase:EXISTE CURSO NA FRASE?ELE COLOCA TRUE(VERDADEIRO)

#frase.replace('python','android')REPLCE SIGNIFICA TROCAR
#ONDE ESTIVER A PALAVRA PYTHON ELE TROCA POR ANDROID

#frase.upper():PARA CIMA VAI FICAR EM MAIUSCULAS
#frase.lower():CONTRARIO DO UPPER, MANTEM O QUE É MINUSCULA E O QUE ESTA
# MAIUSCULA VIRA MINUSCULA

#frase.capitalise(): JOGA TODOS OS CARACTERES PARA MINUSCULO E SO O 1°
# CARACTERE FICA EM MAIUSCULO
#frase.title():ANALISE QUANTAS PALAVRAS TEM NESTA STRING PALAVRA POR PALAVRA O
# INICIO DELAS EM MAIUSCULA POR EXEMPLO: Curso Em Video Python SÓ O INICIO DAS PALAVRAS
# FICARAM EM MAIUSCULA.


#TRANSFORMAÇÃO:

#[][][][A][p][r][e][n][d][a][][P][y][t][h][o][n][][]
#0                                                18

#frase.strip():REMOVE TODOS OS ESPAÇOS INUTEIS NO INICIO E DO FIM DA STRING
#frase.rstrip() O r SIGNIFICA DIREITA: REMOVE SOMENTE OS ULTIMOS ESPAÇOS.
#frase.lstrip() O l SIGNIFICA ESQUERDA:REMOVE SOMENTE DAS ESQUERDA.

#DIVISÃO:
#frase.split():DIVISÃO ENTRE OS ESPAÇOS ENTRE AS PALAVRAS.

#"-"join(frase):IRÁ JUNTAR TODOS OS ELEMENTOS DE FRASE E IRA USAR ESTE SEPARADOR NESTE CASO
# O -. CURSO-EM-VIDEO-PYTHON.
#

